site_name: LgxTpre's Warehouse
site_url: https://lgxtpre.github.io
site_author: LgxTpre
strict: false

theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
    - scheme: slate
      primary: black
      accent: white
      toggle: 
        icon: material/brightness-4
        name: 切换至白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand
    - search.share
  language: zh
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

edit_uri: edit/main/docs
repo_url: https://github.com/LgxTpre/lgxtpre.github.io
repo_name: LgxTpre's Warehouse

copyright: Copyright &copy; 2023 LgxTpre

hooks:
  - hooks/on_env.py

nav:  
  - Home:
    - Start: index.md
    - 常用缺省源: default_source.md
    - AT/CF缺省源: ATCF_default_source.md
  - 图论: 
    - 最短路相关: graph/shortpath.md
    - 最小生成树: graph/MST.md
    - tarjan: graph/tarjan.md
    - 网络流: graph/flow.md
  - 数据结构:  
    - 并查集: ds/DSU.md
    - LCT: ds/LCT.md
  - 数论:
    - 筛法: math/Sieve.md
    - Pollard_Rho: math/Pollard_Rho.md

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lgxtpre
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1475259438@qq.com>

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - 'site_config/static/js/math-csr.js?math-csr'
  - 'site_config/assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'

extra_css:
  - 'site_config/static/css/extra.css?v=14'
